version: "3"

services:
  database:
    image: postgres:16.4
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    image: p21-desafio-app
    build:
      context: .
    ports:
      - 8080:8080
    user: "${UID}:${GID}"
    volumes:
      - ./:/app/:z
    
    # ADICIONE ESTE BLOCO DE AMBIENTE:
    environment:
      # O HOST deve ser o nome do serviço do DB no Docker Compose
      DB_HOST: database  # Isso permite que a app encontre o DB dentro da rede Docker
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      # Você pode adicionar o nome do banco de dados principal aqui (se for diferente de 'postgres')
      DB_NAME: postgres 
      
    command: yarn start:dev

volumes:
  database:
